---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - src: 'ansibleguy.infra_certs'
  - src: 'ansibleguy.infra_mariadb'
  - src: 'ansibleguy.infra_nginx'

collections:
  - 'community.mysql'
  - 'ansible.posix'
  - 'community.crypto'
