---

- name: iRedMail | Showing debug info - user provided config
  ansible.builtin.debug:
    var: iredmail
  when:
    - debug is defined
    - debug

- name: iRedMail | Showing debug info - running config
  ansible.builtin.debug:
    var: IRM_CONFIG
  when:
    - debug is defined
    - debug

- name: iRedMail | Checking config
  ansible.builtin.assert:
    that:
      - IRM_CONFIG.fqdn is defined
      - IRM_CONFIG.fqdn | valid_hostname

- name: iRedMail | Setting domain
  ansible.builtin.set_fact:
    irm_domain: "{{ IRM_CONFIG.fqdn | remove_hostname }}"
    irm_host_sub_domain: "{{ IRM_CONFIG.fqdn | get_subdomain }}"

- name: iRedMail | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"

- name: iRedMail | Cleaning up temporary password files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  delegate_to: localhost
  become: false
  changed_when: false
  loop:
    - "{{ tmp_pwd_file_prefix }}_admin"
    - "{{ tmp_pwd_file_prefix }}_mysql_ph"
    - "{{ tmp_pwd_file_prefix }}_mysql_vmail"
    - "{{ tmp_pwd_file_prefix }}_mysql_vadm"
    - "{{ tmp_pwd_file_prefix }}_mysql_sogo"
    - "{{ tmp_pwd_file_prefix }}_mysql_iradm"
    - "{{ tmp_pwd_file_prefix }}_mysql_iradb"
    - "{{ tmp_pwd_file_prefix }}_mysql_rcm"
    - "{{ tmp_pwd_file_prefix }}_mysql_ava"
    - "{{ tmp_pwd_file_prefix }}_mysql_nd"
    - "{{ tmp_pwd_file_prefix }}_mysql_f2b"
