---

- name: iRedMail | Checking config
  ansible.builtin.assert:
    that:
      - IRM_CONFIG.domain is defined
      - IRM_CONFIG.mailserver_sub_domain is defined

- name: iRedMail | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"

- name: iRedMail | Cleaning up temporary password files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tmp_pwd_file_prefix }}_admin"
    - "{{ tmp_pwd_file_prefix }}_mysql"
