---

- name: Converge
  hosts: grp_targets
  vars:
    no_prompts: true
    iredmail:
      fqdn: 'mail.iredmail.test.ansibleguy.net'
       manage:
         sogo: true

      config:
        admin_user: 'postmaster'

      nginx:
        aliases: ['alias.lan', '_']
        ip: '192.168.5.2'
        ssl:
          mode: 'ca'

  roles:
    - ansibleguy.sw_iredmail
