---

- name: Converge
  hosts: grp_targets
  vars:
    no_prompts: true
    iredmail:
      domain: 'iredmail.test.ansibleguy.net'
      mailserver_sub_domain: 'mail'
      # manage:
      #   sogo: true

      config:
        admin_user: 'postmaster'

      nginx:
        aliases: ['alias.lan', '_']
        ip: '192.168.5.2'
        ssl:
          mode: 'ca'

  roles:
    - ansibleguy.sw_iredmail
